### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by rodsnjr** [yelirekim/php-introspector#1]
[Enter steps to reproduce below:]
Using on a second sccreen, with a ".blade.php" file ...

It keeps happening in any php line! annoying!
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [php-introspector](https://github.com/yelirekim/php-introspector) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At C:\Users\Rodney\.atom\packages\php-introspector\lib\suggestions-client.coffee:9

TypeError: Cannot read property 'then' of undefined
  at PhpIntrospectorSuggestionsClient.module.exports.PhpIntrospectorSuggestionsClient.complete (C:\Users\Rodney\.atom\packages\php-introspector\lib\suggestions-client.coffee:9:26)
  at PhpIntrospectorCompletionProvider.module.exports.PhpIntrospectorCompletionProvider.getSuggestions (C:\Users\Rodney\.atom\packages\php-introspector\lib\completion-provider.coffee:12:12)
  at C:\Users\Rodney\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:255:56
  at Array.forEach (native)
  at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (C:\Users\Rodney\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:234:17)
  at AutocompleteManager.getSuggestionsFromProviders (C:\Users\Rodney\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
  at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (C:\Users\Rodney\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:221:19)
  at C:\Users\Rodney\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61

```
### Commands

```
     -1:53.1.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -1:52.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:51.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:36.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:31.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:24.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -0:38.9.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:31.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:29.8.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:22.7.0 core:delete (atom-text-editor.editor.is-focused)
     -0:22.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:19.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:18.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:17.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:03.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-autocomplete-php, vundefined
css-snippets, v0.8.0
git-go, v1.0.1
language-blade, v0.14.0
laravel, v0.7.0
php-debug, v0.1.2
php-introspector, v1.0.0
tualo-git-context, v0.6.11

# Dev
No dev packages
```

**Comment by posthuman-resource** [comment]
I really, really appreciate you using this package.  However, it's currently super broken, and barely functional.

If you have any more issues, please feel free to contribute, or file them here.  I'll be working on this as time permits.
